//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NoobTD_ImageGrayWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NoobTD.ImageGray), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("TurnGray", TurnGray);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int TurnGray(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			NoobTD.ImageGray obj = (NoobTD.ImageGray)ToLua.CheckObject<NoobTD.ImageGray>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.TurnGray(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

