//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class NoobTD_AdsManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(NoobTD.AdsManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("ShowNormal", ShowNormal);
		L.RegFunction("ShowRewarded", ShowRewarded);
		L.RegFunction("ShowRewarded2", ShowRewarded2);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("testMode", get_testMode, set_testMode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowNormal(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NoobTD.AdsManager obj = (NoobTD.AdsManager)ToLua.CheckObject<NoobTD.AdsManager>(L, 1);
			obj.ShowNormal();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowRewarded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NoobTD.AdsManager obj = (NoobTD.AdsManager)ToLua.CheckObject<NoobTD.AdsManager>(L, 1);
			obj.ShowRewarded();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ShowRewarded2(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			NoobTD.AdsManager obj = (NoobTD.AdsManager)ToLua.CheckObject<NoobTD.AdsManager>(L, 1);
			obj.ShowRewarded2();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_testMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NoobTD.AdsManager obj = (NoobTD.AdsManager)o;
			bool ret = obj.testMode;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index testMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_testMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			NoobTD.AdsManager obj = (NoobTD.AdsManager)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.testMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index testMode on a nil value");
		}
	}
}

