--UI: Namespace
-------------------------------
UI = {}

require("UI/Window/WindowBase")
require("UI/Item/ItemBase")

UI.Manager                      = require("UI/UIManager")



-- UI.TestItem                     = require("UI/Item/TestItem")
-- UI.MatHPBar                     = require("UI/Item/MatHPBar")
-- UI.StaffItem                    = require("UI/Item/StaffItem")
-- UI.GameItem                     = require("UI/Item/GameItem")
UI.SystemTipItem                = require("UI/Item/SystemTipItem")
UI.SystemPopupItem              = require("UI/Item/SystemPopupItem")
-- UI.GameTypeItem                 = require("UI/Item/GameTypeItem")
-- UI.GameThemeItem                = require("UI/Item/GameThemeItem")
-- UI.GameConsoleItem              = require("UI/Item/GameConsoleItem")
-- UI.TrainItem                    = require("UI/Item/TrainItem")
-- UI.JobItem                      = require("UI/Item/JobItem")
-- UI.GameAttributeItem            = require("UI/Item/GameAttributeItem")
-- UI.CEItem                       = require("UI/Item/CEItem")
-- UI.SaleReportItem               = require("UI/Item/SaleReportItem")
-- UI.NetworkReportItem            = require("UI/Item/NetworkReportItem")
-- UI.SellCountItem                = require("UI/Item/SellCountItem")
-- UI.MenuItem                     = require("UI/Item/MenuItem")
-- UI.MenuOptionItem               = require("UI/Item/MenuOptionItem")
-- UI.MonumentItem                 = require("UI/Item/MonumentItem")
-- UI.AchivementItem               = require("UI/Item/AchivementItem")
-- UI.GameScoreLeftItem            = require("UI/Item/GameScoreLeftItem")
-- UI.GameScoreRightItem           = require("UI/Item/GameScoreRightItem")
-- UI.AttributeItem                = require("UI/Item/AttributeItem")
-- UI.NoticeItem                   = require("UI/Item/NoticeItem")
-- UI.PointItem                    = require("UI/Item/PointItem")
-- UI.GameScoreItem                = require("UI/Item/GameScoreItem")
-- UI.GameSeriesTabItem            = require("UI/Item/GameSeriesTabItem")
-- UI.GameSeriesItem               = require("UI/Item/GameSeriesItem")
-- UI.JobCentreItem                = require("UI/Item/JobCentreItem")
-- UI.ChartNameItem                = require("UI/Item/ChartNameItem")
-- UI.ChartCircleItem              = require("UI/Item/ChartCircleItem")
-- UI.StaffLightItem               = require("UI/Item/StaffLightItem")
-- UI.HardwareItem                 = require("UI/Item/HardwareItem")
-- UI.ConsoleElementItem           = require("UI/Item/ConsoleElementItem")
-- UI.LoanItem                     = require("UI/Item/LoanItem")
-- UI.MessageItem                  = require("UI/Item/MessageItem")
-- UI.GameAgentItem                = require("UI/Item/GameAgentItem")
-- UI.OutsourceItem                = require("UI/Item/OutsourceItem")
-- UI.OutsourceAttributeItem       = require("UI/Item/OutsourceAttributeItem")
-- UI.ExpBarItem                   = require("UI/Item/ExpBarItem")
-- UI.AgentorBarItem               = require("UI/Item/AgentorBarItem")






-- UI.MainWindow                   = require("UI/Window/MainWindow")
-- UI.GameReadyWindow              = require("UI/Window/GameReadyWindow")
-- UI.GameScoreWindow              = require("UI/Window/GameScoreWindow")
UI.SystemPopupWindow            = require("UI/Window/SystemPopupWindow")
-- UI.GameMainWindow               = require("UI/Window/GameMainWindow")
-- UI.GameConsoleWindow            = require("UI/Window/GameConsoleWindow")
-- UI.GameTypeWindow               = require("UI/Window/GameTypeWindow")
-- UI.GameThemeWindow              = require("UI/Window/GameThemeWindow")
-- UI.JobCentreWindow              = require("UI/Window/JobCentreWindow")
-- UI.PlanWindow                   = require("UI/Window/PlanWindow")
-- UI.ArtWindow                    = require("UI/Window/ArtWindow")
-- UI.SchoolWindow                 = require("UI/Window/SchoolWindow")
-- UI.JobUpgradeWindow             = require("UI/Window/JobUpgradeWindow")
-- UI.MenuWindow                   = require("UI/Window/MenuWindow")
-- UI.MonumentWindow               = require("UI/Window/MonumentWindow")
-- UI.StaffMainWindow              = require("UI/Window/StaffMainWindow")
-- UI.GMWindow                     = require("UI/Window/GMWindow")
-- UI.PropagandaWindow             = require("UI/Window/PropagandaWindow")
-- UI.GameSequelWindow             = require("UI/Window/GameSequelWindow")
-- UI.SequelMainWindow             = require("UI/Window/SequelMainWindow")
-- UI.GameSeriesWindow             = require("UI/Window/GameSeriesWindow")
-- UI.JobCentreListWindow          = require("UI/Window/JobCentreListWindow")
-- UI.GameTopTenWindow             = require("UI/Window/GameTopTenWindow")
-- UI.ConsoleMainWindow            = require("UI/Window/ConsoleMainWindow")
-- UI.ConsoleReadyWindow           = require("UI/Window/ConsoleReadyWindow")
-- UI.ConsoleElementWindow         = require("UI/Window/ConsoleElementWindow")
-- UI.BankWindow                   = require("UI/Window/BankWindow")
-- UI.GameListWindow               = require("UI/Window/GameListWindow")
-- UI.FactoryWindow                = require("UI/Window/FactoryWindow")
-- UI.AdvertWindow                 = require("UI/Window/AdvertWindow")
-- UI.FactoryPauseWindow           = require("UI/Window/FactoryPauseWindow")
-- UI.AgentWindow                  = require("UI/Window/AgentWindow")
-- UI.OutsourceWindow              = require("UI/Window/OutsourceWindow")
-- UI.LoginWindow                  = require("UI/Window/LoginWindow")
-- UI.LoadingWindow                = require("UI/Window/LoadingWindow")
-- UI.RegisterWindow               = require("UI/Window/RegisterWindow")
-- UI.RegisterCompanyWindow        = require("UI/Window/RegisterCompanyWindow")
-- UI.AgentorResultWindow          = require("UI/Window/AgentorResultWindow")
-- UI.SidelineWindow               = require("UI/Window/SidelineWindow")
-- UI.FactoryResultWindow          = require("UI/Window/FactoryResultWindow")





UI.PrefabList                   = require("UI/PrefabList")
